import numpy as np
print("ARRAY OPERATIONS")
arr1= np.array([1,2,3])
arr2 =np.array([10,20,30])
print(f"Array 1:{arr1}")
print(f"Array 1:{arr2}")
print(f"Addtion:{arr1}+{arr2}")
print(f"subtraction:{arr1}-{arr2}")
print(f"multiplecation:{arr1}*{arr2}")
print(f"square:{arr1**2},{arr2**2}")
print(f"sum of array1:{np.sum (arr1)}")
print(f"mean of array2:{np.mean(arr2)}")
print(f"standard deviation of Array1:{np.std(arr1)}")
print(f"Elements in array 1 >2:{arr1>2}")
print(f"Elements of array 2<=20:{arr2<=20}")
arr3 =np.arange(1,7)
reshaped = arr3.reshape((2,3))
print(f"Original array:{arr3}")
print(f"Reshaped to 2x3: \n {reshaped}")
math1 = np.array([1,2],[3,4])
math2 =np.array([5,6],[7,8])
result = np.dot(math, math2)
print(f"Matrix 1:\n{math1}")
print(f"Matrix 2:\n{math2}")
